services:
  - type: web
    name: Save Restricted 
    plan: free
    env: docker
    dockerfilePath: Dockerfile
    repo: https://github.com/Siddwap/VJ-Save-Restricted-Content-Colab 
    branch: master
    autoDeploy: false
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: DB_URI
        sync: false
      - key: PORT
        value: 8000  # Default port value, update if needed
